// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM7LPKksOkgTTWVIbKk_YGMt9Yfl3E_Ug',
    appId: '1:591305675153:web:87871d069a6ffda4744a30',
    messagingSenderId: '591305675153',
    projectId: 'dreamingstory-63139',
    authDomain: 'dreamingstory-63139.firebaseapp.com',
    storageBucket: 'dreamingstory-63139.firebasestorage.app',
    measurementId: 'G-8K4YEXZ0G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc7i_Vk4pQ4QfOH6-FISjs4x2fsN40c8U',
    appId: '1:591305675153:android:650773f9a9429fc6744a30',
    messagingSenderId: '591305675153',
    projectId: 'dreamingstory-63139',
    storageBucket: 'dreamingstory-63139.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf64LIjOD2ynQrg3I5hLWYHGaa8p0cyUk',
    appId: '1:591305675153:ios:1f6bb6dc4e26c079744a30',
    messagingSenderId: '591305675153',
    projectId: 'dreamingstory-63139',
    storageBucket: 'dreamingstory-63139.firebasestorage.app',
    iosBundleId: 'com.example.dreamingstory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf64LIjOD2ynQrg3I5hLWYHGaa8p0cyUk',
    appId: '1:591305675153:ios:1f6bb6dc4e26c079744a30',
    messagingSenderId: '591305675153',
    projectId: 'dreamingstory-63139',
    storageBucket: 'dreamingstory-63139.firebasestorage.app',
    iosBundleId: 'com.example.dreamingstory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM7LPKksOkgTTWVIbKk_YGMt9Yfl3E_Ug',
    appId: '1:591305675153:web:5e36fcc972364d56744a30',
    messagingSenderId: '591305675153',
    projectId: 'dreamingstory-63139',
    authDomain: 'dreamingstory-63139.firebaseapp.com',
    storageBucket: 'dreamingstory-63139.firebasestorage.app',
    measurementId: 'G-QWY4V3LY3T',
  );
}
